DROP TABLE IF EXISTS drones;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS groups_and_drones;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS actions_to_do;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_name TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE drones (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  drone_name TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  ip_addr TEXT NOT NULL,
  port TEXT NOT NULL,
  mac_addr TEXT,
  owner_id INTEGER NOT NULL,
  group_id INTEGER,
  FOREIGN KEY (owner_id) REFERENCES user (id),
  FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE groups_and_drones (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    drone_id INTEGER NOT NULL,
    FOREIGN KEY (drone_id) REFERENCES drones (id),
    FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE actions_to_do (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  action_name TEXT UNIQUE NOT NULL
);


